[package]
name = "safe_math"
version = "0.1.0"
edition = "2023"
authors = "xdDudeGuy"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]